using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using GatheringForGood.Models;
using LocSourceNameReferenceLibrary;
using ImageUrlReferenceLibrary;
using GatheringForGood.Data;
using GatheringForGood.Areas.FunctionalLogic;
using GatheringForGood.Areas.Identity.Data;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Threading;
using Microsoft.AspNetCore.Authorization;

namespace GatheringForGood.Controllers
{
    [AllowAnonymous]
    public class UserArticleController : Controller
    {
        private ApplicationDbContext _context = new();
        private IncrementUserReaction _IncrementUserReaction = new();
        private readonly IMemoryCache _memoryCache;
        readonly IWebHostEnvironment _env;

        public UserArticleController(IMemoryCache memoryCache, IWebHostEnvironment env)
        {
            _memoryCache = memoryCache;
            _env = env;
        }

        [HttpGet]
        public async Task<IActionResult> UserArticleAsync()
        {

            ArticlesPageLocSourceNames _ArticlesPageLocSourceNames = new ArticlesPageLocSourceNames();
            SharedCrossPageLocSourceNames _locSourceSharedCrossPageNameReferenceLibrary = new SharedCrossPageLocSourceNames();
            SharedCrossPageImageUrls _SharedCrossPageImageUrlLibrary = new();
            ArticlesPageImageUrls _ArticlesPageImageUrls = new();
            IncrementArticleViews _IncrementArticleViews = new();
            UserArticlePageImageUrls _UserArticlePageImageUrls = new();
            UserArticlePageLocSourceNames _UserArticlePageLocSourceNames = new();
            TreePurchaseOptionsPartialImageUrls _TreePurchaseOptionsPartialImageUrls = new();
            ArticlesPageLocSourceNames _locSourceArticlesPageNameReferenceLibrary = new();

            try
            {

                string data = RouteData.Values["id"].ToString();
                Debug.WriteLine("RouteData.Values: " + data);

                if (data != null && data != "Preview")
                {
                    Debug.WriteLine("data != null && data != Preview");
                    try
                    {
                        ArticleDetails ArticleDetailsList = GetUserArticleDetails.retrieveArticleDataFromDB(data);

                        if (ArticleDetailsList != null)
                        {

                            await _IncrementArticleViews.incrementArticleViews(data);

                            var viewModel = new UserArticleViewModel
                            {
                                ArticleId = "https://gatheringforgood.com/en/UserArticle/UserArticle/" + data,
                                PageTabTitle = _ArticlesPageLocSourceNames.GetLocSourcePageTabTitleNameReferenceForArticlesPage(),
                                LikeIconUrl = _UserArticlePageImageUrls.GetlikeiconThumbnailUrlForAboutPage(),
                                DislikeIconUrl = _UserArticlePageImageUrls.GetdislikeiconThumbnailUrlForAboutPage(),
                                ShockedIconUrl = _UserArticlePageImageUrls.GetshockediconThumbnailUrlForAboutPage(),
                                SupportIconUrl = _UserArticlePageImageUrls.GetsupporticonThumbnailUrlForAboutPage(),
                                QuestionableIconUrl = _UserArticlePageImageUrls.GetquestionableiconThumbnailUrlForAboutPage(),
                                uniqueArticleReference = data,
                                ButtonText = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceButtonTextNameReference(),
                                Title = _ArticlesPageLocSourceNames.GetLocSourceTitleNameReferenceForArticlesPage(),
                                Subtitle = _ArticlesPageLocSourceNames.GetLocSourceSubtitleNameReferenceForArticlesPage(),
                                NavBarHome = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceHomeLabelNameReference(),
                                NavBarNewsfeed = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceNewsfeedLabelNameReference(),
                                NavBarAbout = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceAboutLabelNameReference(),
                                NavBarHelpCenter = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceHelpCenterLabelNameReference(),
                                NavBarRegister = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceRegisterLabelNameReference(),
                                NavBarLogin = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceLoginLabelNameReference(),
                                NavBarLogout = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceLogoutLabelNameReference(),
                                AboutUs = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceAboutUsLabelNameReference(),
                                Articles = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceArticlesLabelNameReference(),
                                CookiesNotice = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceCookiesNoticeLabelNameReference(),
                                PrivacyNotice = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourcePrivacyNoticeLabelNameReference(),
                                ComingSoon = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceComingSoonLabelNameReference(),
                                LikeToSee = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceLikeToSeeLabelNameReference(),
                                Submit = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceSubmitLabelNameReference(),
                                AuthorFirstNameRef = ArticleDetailsList.AuthorFirstName,
                                AuthorLastNameRef = ArticleDetailsList.AuthorLastName,
                                ArticleTitle = ArticleDetailsList.Title,
                                ArticleUserId = ArticleDetailsList.UserId,
                                ArticleTitleImageUrl = ArticleDetailsList.TitleImageUrl,
                                ArticleTitleVideoUrl = ArticleDetailsList.TitleVideoUrl,
                                Para1 = ArticleDetailsList.Para1,
                                Para2 = ArticleDetailsList.Para2,
                                Para3 = ArticleDetailsList.Para3,
                                Para4 = ArticleDetailsList.Para4,
                                Para5 = ArticleDetailsList.Para5,
                                Para6 = ArticleDetailsList.Para6,
                                Para7 = ArticleDetailsList.Para7,
                                Para8 = ArticleDetailsList.Para8,
                                Para9 = ArticleDetailsList.Para9,
                                Para10 = ArticleDetailsList.Para10,
                                Para11 = ArticleDetailsList.Para11,
                                Para12 = ArticleDetailsList.Para12,
                                Para13 = ArticleDetailsList.Para13,
                                Para14 = ArticleDetailsList.Para14,
                                Para15 = ArticleDetailsList.Para15,
                                Para16 = ArticleDetailsList.Para16,
                                Para17 = ArticleDetailsList.Para17,
                                Para18 = ArticleDetailsList.Para18,
                                Para19 = ArticleDetailsList.Para19,
                                Para20 = ArticleDetailsList.Para20,
                                Para21 = ArticleDetailsList.Para21,
                                Para22 = ArticleDetailsList.Para22,
                                Para23 = ArticleDetailsList.Para23,
                                Para24 = ArticleDetailsList.Para24,
                                Para25 = ArticleDetailsList.Para25,
                                Para26 = ArticleDetailsList.Para26,
                                Para27 = ArticleDetailsList.Para27,
                                Para28 = ArticleDetailsList.Para28,
                                Para29 = ArticleDetailsList.Para29,
                                Para30 = ArticleDetailsList.Para30,
                                Para31 = ArticleDetailsList.Para31,
                                Para32 = ArticleDetailsList.Para32,
                                Para33 = ArticleDetailsList.Para33,
                                Para34 = ArticleDetailsList.Para34,
                                Para35 = ArticleDetailsList.Para35,
                                Para36 = ArticleDetailsList.Para36,
                                Para37 = ArticleDetailsList.Para37,
                                Para38 = ArticleDetailsList.Para38,
                                Para39 = ArticleDetailsList.Para39,
                                Para40 = ArticleDetailsList.Para40,
                                Para41 = ArticleDetailsList.Para41,
                                Para42 = ArticleDetailsList.Para42,
                                Para43 = ArticleDetailsList.Para43,
                                Para44 = ArticleDetailsList.Para44,
                                Para45 = ArticleDetailsList.Para45,
                                Para46 = ArticleDetailsList.Para46,
                                Para47 = ArticleDetailsList.Para47,
                                Para48 = ArticleDetailsList.Para48,
                                Para49 = ArticleDetailsList.Para49,
                                Para50 = ArticleDetailsList.Para50,
                                Para2Subheading = ArticleDetailsList.Para2Subheading,
                                Para3Subheading = ArticleDetailsList.Para3Subheading,
                                Para4Subheading = ArticleDetailsList.Para4Subheading,
                                Para5Subheading = ArticleDetailsList.Para5Subheading,
                                Para6Subheading = ArticleDetailsList.Para6Subheading,
                                Para7Subheading = ArticleDetailsList.Para7Subheading,
                                Para8Subheading = ArticleDetailsList.Para8Subheading,
                                Para9Subheading = ArticleDetailsList.Para9Subheading,
                                Para10Subheading = ArticleDetailsList.Para10Subheading,
                                Para11Subheading = ArticleDetailsList.Para11Subheading,
                                Para12Subheading = ArticleDetailsList.Para12Subheading,
                                Para13Subheading = ArticleDetailsList.Para13Subheading,
                                Para14Subheading = ArticleDetailsList.Para14Subheading,
                                Para15Subheading = ArticleDetailsList.Para15Subheading,
                                Para16Subheading = ArticleDetailsList.Para16Subheading,
                                Para17Subheading = ArticleDetailsList.Para17Subheading,
                                Para18Subheading = ArticleDetailsList.Para18Subheading,
                                Para19Subheading = ArticleDetailsList.Para19Subheading,
                                Para20Subheading = ArticleDetailsList.Para20Subheading,
                                Para21Subheading = ArticleDetailsList.Para21Subheading,
                                Para22Subheading = ArticleDetailsList.Para22Subheading,
                                Para23Subheading = ArticleDetailsList.Para23Subheading,
                                Para24Subheading = ArticleDetailsList.Para24Subheading,
                                Para25Subheading = ArticleDetailsList.Para25Subheading,
                                Para26Subheading = ArticleDetailsList.Para26Subheading,
                                Para27Subheading = ArticleDetailsList.Para27Subheading,
                                Para28Subheading = ArticleDetailsList.Para28Subheading,
                                Para29Subheading = ArticleDetailsList.Para29Subheading,
                                Para30Subheading = ArticleDetailsList.Para30Subheading,
                                Para31Subheading = ArticleDetailsList.Para31Subheading,
                                Para32Subheading = ArticleDetailsList.Para32Subheading,
                                Para33Subheading = ArticleDetailsList.Para33Subheading,
                                Para34Subheading = ArticleDetailsList.Para34Subheading,
                                Para35Subheading = ArticleDetailsList.Para35Subheading,
                                Para36Subheading = ArticleDetailsList.Para36Subheading,
                                Para37Subheading = ArticleDetailsList.Para37Subheading,
                                Para38Subheading = ArticleDetailsList.Para38Subheading,
                                Para39Subheading = ArticleDetailsList.Para39Subheading,
                                Para40Subheading = ArticleDetailsList.Para40Subheading,
                                Para41Subheading = ArticleDetailsList.Para41Subheading,
                                Para42Subheading = ArticleDetailsList.Para42Subheading,
                                Para43Subheading = ArticleDetailsList.Para43Subheading,
                                Para44Subheading = ArticleDetailsList.Para44Subheading,
                                Para45Subheading = ArticleDetailsList.Para45Subheading,
                                Para46Subheading = ArticleDetailsList.Para46Subheading,
                                Para47Subheading = ArticleDetailsList.Para47Subheading,
                                Para48Subheading = ArticleDetailsList.Para48Subheading,
                                Para49Subheading = ArticleDetailsList.Para49Subheading,
                                Para50Subheading = ArticleDetailsList.Para50Subheading,
                                ImageTitleCaption = ArticleDetailsList.ImageTitleCaption,
                                Image2Caption = ArticleDetailsList.Image2Caption,
                                Image3Caption = ArticleDetailsList.Image3Caption,
                                Image4Caption = ArticleDetailsList.Image4Caption,
                                Image5Caption = ArticleDetailsList.Image5Caption,
                                Image6Caption = ArticleDetailsList.Image6Caption,
                                Image7Caption = ArticleDetailsList.Image7Caption,
                                Image8Caption = ArticleDetailsList.Image8Caption,
                                Image9Caption = ArticleDetailsList.Image9Caption,
                                Image10Caption = ArticleDetailsList.Image10Caption,
                                Image11Caption = ArticleDetailsList.Image11Caption,
                                Image12Caption = ArticleDetailsList.Image12Caption,
                                Image13Caption = ArticleDetailsList.Image13Caption,
                                Image14Caption = ArticleDetailsList.Image14Caption,
                                Image15Caption = ArticleDetailsList.Image15Caption,
                                Image16Caption = ArticleDetailsList.Image16Caption,
                                Image17Caption = ArticleDetailsList.Image17Caption,
                                Image18Caption = ArticleDetailsList.Image18Caption,
                                Image19Caption = ArticleDetailsList.Image19Caption,
                                Image20Caption = ArticleDetailsList.Image20Caption,
                                Image21Caption = ArticleDetailsList.Image21Caption,
                                Image22Caption = ArticleDetailsList.Image22Caption,
                                Image23Caption = ArticleDetailsList.Image23Caption,
                                Image24Caption = ArticleDetailsList.Image24Caption,
                                Image25Caption = ArticleDetailsList.Image25Caption,
                                Image26Caption = ArticleDetailsList.Image26Caption,
                                Image27Caption = ArticleDetailsList.Image27Caption,
                                Image28Caption = ArticleDetailsList.Image28Caption,
                                Image29Caption = ArticleDetailsList.Image29Caption,
                                Image30Caption = ArticleDetailsList.Image30Caption,
                                Image31Caption = ArticleDetailsList.Image31Caption,
                                Image32Caption = ArticleDetailsList.Image32Caption,
                                Image33Caption = ArticleDetailsList.Image33Caption,
                                Image34Caption = ArticleDetailsList.Image34Caption,
                                Image35Caption = ArticleDetailsList.Image35Caption,
                                Image36Caption = ArticleDetailsList.Image36Caption,
                                Image37Caption = ArticleDetailsList.Image37Caption,
                                Image38Caption = ArticleDetailsList.Image38Caption,
                                Image39Caption = ArticleDetailsList.Image39Caption,
                                Image40Caption = ArticleDetailsList.Image40Caption,
                                Image41Caption = ArticleDetailsList.Image41Caption,
                                Image42Caption = ArticleDetailsList.Image42Caption,
                                Image43Caption = ArticleDetailsList.Image43Caption,
                                Image44Caption = ArticleDetailsList.Image44Caption,
                                Image45Caption = ArticleDetailsList.Image45Caption,
                                Image46Caption = ArticleDetailsList.Image46Caption,
                                Image47Caption = ArticleDetailsList.Image47Caption,
                                Image48Caption = ArticleDetailsList.Image48Caption,
                                Image49Caption = ArticleDetailsList.Image49Caption,
                                Image50Caption = ArticleDetailsList.Image50Caption,
                                Image1 = ArticleDetailsList.Image1,
                                Image2 = ArticleDetailsList.Image2,
                                Image3 = ArticleDetailsList.Image3,
                                Image4 = ArticleDetailsList.Image4,
                                Image5 = ArticleDetailsList.Image5,
                                Image6 = ArticleDetailsList.Image6,
                                Image7 = ArticleDetailsList.Image7,
                                Image8 = ArticleDetailsList.Image8,
                                Image9 = ArticleDetailsList.Image9,
                                Image10 = ArticleDetailsList.Image10,
                                Image11 = ArticleDetailsList.Image11,
                                Image12 = ArticleDetailsList.Image12,
                                Image13 = ArticleDetailsList.Image13,
                                Image14 = ArticleDetailsList.Image14,
                                Image15 = ArticleDetailsList.Image15,
                                Image16 = ArticleDetailsList.Image16,
                                Image17 = ArticleDetailsList.Image17,
                                Image18 = ArticleDetailsList.Image18,
                                Image19 = ArticleDetailsList.Image19,
                                Image20 = ArticleDetailsList.Image20,
                                Image21 = ArticleDetailsList.Image21,
                                Image22 = ArticleDetailsList.Image22,
                                Image23 = ArticleDetailsList.Image23,
                                Image24 = ArticleDetailsList.Image24,
                                Image25 = ArticleDetailsList.Image25,
                                Image26 = ArticleDetailsList.Image26,
                                Image27 = ArticleDetailsList.Image27,
                                Image28 = ArticleDetailsList.Image28,
                                Image29 = ArticleDetailsList.Image29,
                                Image30 = ArticleDetailsList.Image30,
                                Image31 = ArticleDetailsList.Image31,
                                Image32 = ArticleDetailsList.Image32,
                                Image33 = ArticleDetailsList.Image33,
                                Image34 = ArticleDetailsList.Image34,
                                Image35 = ArticleDetailsList.Image35,
                                Image36 = ArticleDetailsList.Image36,
                                Image37 = ArticleDetailsList.Image37,
                                Image38 = ArticleDetailsList.Image38,
                                Image39 = ArticleDetailsList.Image39,
                                Image40 = ArticleDetailsList.Image40,
                                Image41 = ArticleDetailsList.Image41,
                                Image42 = ArticleDetailsList.Image42,
                                Image43 = ArticleDetailsList.Image43,
                                Image44 = ArticleDetailsList.Image44,
                                Image45 = ArticleDetailsList.Image45,
                                Image46 = ArticleDetailsList.Image46,
                                Image47 = ArticleDetailsList.Image47,
                                Image48 = ArticleDetailsList.Image48,
                                Image49 = ArticleDetailsList.Image49,
                                Image50 = ArticleDetailsList.Image50,
                                Video1 = ArticleDetailsList.Video1,
                                Video2 = ArticleDetailsList.Video2,
                                Video3 = ArticleDetailsList.Video3,
                                Video4 = ArticleDetailsList.Video4,
                                Video5 = ArticleDetailsList.Video5,
                                Video6 = ArticleDetailsList.Video6,
                                Video7 = ArticleDetailsList.Video7,
                                Video8 = ArticleDetailsList.Video8,
                                Video9 = ArticleDetailsList.Video9,
                                Video10 = ArticleDetailsList.Video10,
                                Video11 = ArticleDetailsList.Video11,
                                Video12 = ArticleDetailsList.Video12,
                                Video13 = ArticleDetailsList.Video13,
                                Video14 = ArticleDetailsList.Video14,
                                Video15 = ArticleDetailsList.Video15,
                                Video16 = ArticleDetailsList.Video16,
                                Video17 = ArticleDetailsList.Video17,
                                Video18 = ArticleDetailsList.Video18,
                                Video19 = ArticleDetailsList.Video19,
                                Video20 = ArticleDetailsList.Video20,
                                Video21 = ArticleDetailsList.Video21,
                                Video22 = ArticleDetailsList.Video22,
                                Video23 = ArticleDetailsList.Video23,
                                Video24 = ArticleDetailsList.Video24,
                                Video25 = ArticleDetailsList.Video25,
                                Video26 = ArticleDetailsList.Video26,
                                Video27 = ArticleDetailsList.Video27,
                                Video28 = ArticleDetailsList.Video28,
                                Video29 = ArticleDetailsList.Video29,
                                Video30 = ArticleDetailsList.Video30,
                                Video31 = ArticleDetailsList.Video31,
                                Video32 = ArticleDetailsList.Video32,
                                Video33 = ArticleDetailsList.Video33,
                                Video34 = ArticleDetailsList.Video34,
                                Video35 = ArticleDetailsList.Video35,
                                Video36 = ArticleDetailsList.Video36,
                                Video37 = ArticleDetailsList.Video37,
                                Video38 = ArticleDetailsList.Video38,
                                Video39 = ArticleDetailsList.Video39,
                                Video40 = ArticleDetailsList.Video40,
                                Video41 = ArticleDetailsList.Video41,
                                Video42 = ArticleDetailsList.Video42,
                                Video43 = ArticleDetailsList.Video43,
                                Video44 = ArticleDetailsList.Video44,
                                Video45 = ArticleDetailsList.Video45,
                                Video46 = ArticleDetailsList.Video46,
                                Video47 = ArticleDetailsList.Video47,
                                Video48 = ArticleDetailsList.Video48,
                                Video49 = ArticleDetailsList.Video49,
                                Video50 = ArticleDetailsList.Video50,
                                LikeCount = ArticleDetailsList.Likes,
                                DislikeCount = ArticleDetailsList.Dislikes,
                                SupportCount = ArticleDetailsList.Support,
                                QuestionableCount = ArticleDetailsList.Questionable,
                                ShockedCount = ArticleDetailsList.Shocked,
                                Featured = ArticleDetailsList.Featured,
                                TreePlanted = ArticleDetailsList.TreePlanted,
                                Context = _context,
                                PostedDateTime = ArticleDetailsList.PostedDateTime.ToString(),
                                GoBack = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceGoBackNameReferenceForPage(),
                                Updates = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceUpdatesNameReferenceForPage(),
                                UserArticleShare = "https://twitter.com/intent/tweet?hashtags=gatheringforgood%2Cclimatechange%2Cmakeadifference&original_referer=https%3A%2F%2Fgatheringforgood.com%2Fen%2FUserArticle%2FUserArticle%2F" + data + "&ref_src=twsrc%5Etfw%7Ctwcamp%5Ebuttonembed%7Ctwterm%5Eshare%7Ctwgr%5E&text=GatheringForGood%20users%20are%20taking%20action%20to%20help%20save%20the%20world!%20Check%20out%20the%20latest%20user%20article%20'" + ArticleDetailsList.Title + "', and%20help%20make%20a%20difference!%20%F0%9F%98%8A&url=https%3A%2F%2Fgatheringforgood.com%2Fen%2FUserArticle%2FUserArticle%2F" + data,
                                HomepageShare = "https://twitter.com/intent/tweet?hashtags=gatheringforgood%2Cclimatechange%2Cmakeadifference&original_referer=https%3A%2F%2Fgatheringforgood.com%2Fen%2FArticles%2FArticles&ref_src=twsrc%5Etfw%7Ctwcamp%5Ebuttonembed%7Ctwterm%5Eshare%7Ctwgr%5E&text=GatheringForGood%20users%20are%20taking%20action%20to%20help%20save%20the%20world!%20Check%20out%20the%20latest%20user%20article%20'" + ArticleDetailsList.Title + "', and%20help%20make%20a%20difference!%20%F0%9F%98%8A&url=https%3A%2F%2Fgatheringforgood.com%2Fen%2FUserArticle%2FUserArticle%2F" + data,
                                IconTwitter = _SharedCrossPageImageUrlLibrary.GetTwitterIconUrlForPage(),
                                IconLinkedin = _SharedCrossPageImageUrlLibrary.GetLinkedinIconUrlForPage(),
                                IconFacebook = _SharedCrossPageImageUrlLibrary.GetFacebookIconUrlForPage(),
                                FeaturedArticleUrl = _ArticlesPageImageUrls.GetFeaturedNoPaddingArticleImageThumbnailUrlForArticlesPage(),
                                TreePlantedUrl = _TreePurchaseOptionsPartialImageUrls.Get1TreeIconImageThumbnailUrlForAboutPage(),
                                FeaturedTitle = _locSourceArticlesPageNameReferenceLibrary.GetLocSourceFeaturedNameTitleReferenceForArticlesPage(),
                                FeaturedText = _locSourceArticlesPageNameReferenceLibrary.GetLocSourceFeaturedInfoNameReferenceForArticlesPage(),
                                TreePurchaseTitle = _locSourceArticlesPageNameReferenceLibrary.GetLocSourceTreePurchasedTitleNameReferenceForArticlesPage(),
                                TreePurchaseText = _locSourceArticlesPageNameReferenceLibrary.GetLocSourceTreePurchasedInfoNameReferenceForArticlesPage(),
                                LikeTooltip = _UserArticlePageLocSourceNames.GetLocSourceLikeTooltipNameReferenceForArticlesPage(),
                                DislikeTooltip = _UserArticlePageLocSourceNames.GetLocSourceDislikeTooltipNameReferenceForArticlesPage(),
                                SupportTooltip = _UserArticlePageLocSourceNames.GetLocSourceSupportTooltipNameReferenceForArticlesPage(),
                                QuestionableTooltip = _UserArticlePageLocSourceNames.GetLocSourceQuestionableTooltipNameReferenceForArticlesPage(),
                                ShockedTooltip = _UserArticlePageLocSourceNames.GetLocSourceShockedTooltipNameReferenceForArticlesPage(),
                                GetEarthHandsReducedImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReducedImageUrlForPage(),
                                GetEarthHandsReduced400ImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReduced400ImageUrlForPage(),
                                GetEarthHandsReduced800ImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReduced800ImageUrlForPage(),
                                GetEarthHandsReduced1200ImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReduced1200ImageUrlForPage(),
                                GetEarthHandsReduced1600ImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReduced1600ImageUrlForPage()
                            };
                            return View(viewModel);
                        }
                        else
                        {
                            return LocalRedirect("~/Articles/Articles");
                        }
                    }
                    catch (Exception e)
                    {
                        Debug.WriteLine(e.GetType().ToString());
                        return LocalRedirect("~/Articles/Articles");
                    }
                }
                else if (data == "Preview")
                {
                    Debug.WriteLine("data == Preview");
                    try
                    {
                        Debug.WriteLine("try");
                        var viewModel = new UserArticleViewModel
                            {
                                ArticleId = "https://gatheringforgood.com/en/UserArticle/UserArticle/Preview",
                                PageTabTitle = _ArticlesPageLocSourceNames.GetLocSourcePageTabTitleNameReferenceForArticlesPage(),
                                LikeIconUrl = _UserArticlePageImageUrls.GetlikeiconThumbnailUrlForAboutPage(),
                                DislikeIconUrl = _UserArticlePageImageUrls.GetdislikeiconThumbnailUrlForAboutPage(),
                                ShockedIconUrl = _UserArticlePageImageUrls.GetshockediconThumbnailUrlForAboutPage(),
                                SupportIconUrl = _UserArticlePageImageUrls.GetsupporticonThumbnailUrlForAboutPage(),
                                QuestionableIconUrl = _UserArticlePageImageUrls.GetquestionableiconThumbnailUrlForAboutPage(),
                                uniqueArticleReference = data,
                                ButtonText = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceButtonTextNameReference(),
                                Title = _ArticlesPageLocSourceNames.GetLocSourceTitleNameReferenceForArticlesPage(),
                                Subtitle = _ArticlesPageLocSourceNames.GetLocSourceSubtitleNameReferenceForArticlesPage(),
                                NavBarHome = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceHomeLabelNameReference(),
                                NavBarNewsfeed = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceNewsfeedLabelNameReference(),
                                NavBarAbout = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceAboutLabelNameReference(),
                                NavBarHelpCenter = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceHelpCenterLabelNameReference(),
                                NavBarRegister = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceRegisterLabelNameReference(),
                                NavBarLogin = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceLoginLabelNameReference(),
                                NavBarLogout = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceLogoutLabelNameReference(),
                                AboutUs = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceAboutUsLabelNameReference(),
                                Articles = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceArticlesLabelNameReference(),
                                CookiesNotice = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceCookiesNoticeLabelNameReference(),
                                PrivacyNotice = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourcePrivacyNoticeLabelNameReference(),
                                ComingSoon = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceComingSoonLabelNameReference(),
                                LikeToSee = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceLikeToSeeLabelNameReference(),
                                Submit = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceSubmitLabelNameReference(),
                                AuthorFirstNameRef = _memoryCache.Get<string>("AuthorFirstName"),
                                AuthorLastNameRef = _memoryCache.Get<string>("AuthorLastName"),
                                ArticleTitle = _memoryCache.Get<string>("TitleField"),
                                ArticleUserId = _memoryCache.Get<string>("UserIDValue"),
                                ArticleTitleImageUrl = _memoryCache.Get<string>("TitleImageUrl"),
                                ArticleTitleVideoUrl = _memoryCache.Get<string>("TitleVideoUrl"),
                                Para1 = _memoryCache.Get<string>("Para1Field"),
                                Para2 = _memoryCache.Get<string>("Para2Field"),
                                Para3 = _memoryCache.Get<string>("Para3Field"),
                                Para4 = _memoryCache.Get<string>("Para4Field"),
                                Para5 = _memoryCache.Get<string>("Para5Field"),
                                Para6 = _memoryCache.Get<string>("Para6Field"),
                                Para7 = _memoryCache.Get<string>("Para7Field"),
                                Para8 = _memoryCache.Get<string>("Para8Field"),
                                Para9 = _memoryCache.Get<string>("Para9Field"),
                                Para10 = _memoryCache.Get<string>("Para10Field"),
                                Para11 = _memoryCache.Get<string>("Para11Field"),
                                Para12 = _memoryCache.Get<string>("Para12Field"),
                                Para13 = _memoryCache.Get<string>("Para13Field"),
                                Para14 = _memoryCache.Get<string>("Para14Field"),
                                Para15 = _memoryCache.Get<string>("Para15Field"),
                                Para16 = _memoryCache.Get<string>("Para16Field"),
                                Para17 = _memoryCache.Get<string>("Para17Field"),
                                Para18 = _memoryCache.Get<string>("Para18Field"),
                                Para19 = _memoryCache.Get<string>("Para19Field"),
                                Para20 = _memoryCache.Get<string>("Para20Field"),
                                Para21 = _memoryCache.Get<string>("Para21Field"),
                                Para22 = _memoryCache.Get<string>("Para22Field"),
                                Para23 = _memoryCache.Get<string>("Para23Field"),
                                Para24 = _memoryCache.Get<string>("Para24Field"),
                                Para25 = _memoryCache.Get<string>("Para25Field"),
                                Para26 = _memoryCache.Get<string>("Para26Field"),
                                Para27 = _memoryCache.Get<string>("Para27Field"),
                                Para28 = _memoryCache.Get<string>("Para28Field"),
                                Para29 = _memoryCache.Get<string>("Para29Field"),
                                Para30 = _memoryCache.Get<string>("Para30Field"),
                                Para31 = _memoryCache.Get<string>("Para31Field"),
                                Para32 = _memoryCache.Get<string>("Para32Field"),
                                Para33 = _memoryCache.Get<string>("Para33Field"),
                                Para34 = _memoryCache.Get<string>("Para34Field"),
                                Para35 = _memoryCache.Get<string>("Para35Field"),
                                Para36 = _memoryCache.Get<string>("Para36Field"),
                                Para37 = _memoryCache.Get<string>("Para37Field"),
                                Para38 = _memoryCache.Get<string>("Para38Field"),
                                Para39 = _memoryCache.Get<string>("Para39Field"),
                                Para40 = _memoryCache.Get<string>("Para40Field"),
                                Para41 = _memoryCache.Get<string>("Para41Field"),
                                Para42 = _memoryCache.Get<string>("Para42Field"),
                                Para43 = _memoryCache.Get<string>("Para43Field"),
                                Para44 = _memoryCache.Get<string>("Para44Field"),
                                Para45 = _memoryCache.Get<string>("Para45Field"),
                                Para46 = _memoryCache.Get<string>("Para46Field"),
                                Para47 = _memoryCache.Get<string>("Para47Field"),
                                Para48 = _memoryCache.Get<string>("Para48Field"),
                                Para49 = _memoryCache.Get<string>("Para49Field"),
                                Para50 = _memoryCache.Get<string>("Para50Field"),
                                Para2Subheading = _memoryCache.Get<string>("Para2SubheadingField"),
                                Para3Subheading = _memoryCache.Get<string>("Para3SubheadingField"),
                                Para4Subheading = _memoryCache.Get<string>("Para4SubheadingField"),
                                Para5Subheading = _memoryCache.Get<string>("Para5SubheadingField"),
                                Para6Subheading = _memoryCache.Get<string>("Para6SubheadingField"),
                                Para7Subheading = _memoryCache.Get<string>("Para7SubheadingField"),
                                Para8Subheading = _memoryCache.Get<string>("Para8SubheadingField"),
                                Para9Subheading = _memoryCache.Get<string>("Para9SubheadingField"),
                                Para10Subheading = _memoryCache.Get<string>("Para10SubheadingField"),
                                Para11Subheading = _memoryCache.Get<string>("Para11SubheadingField"),
                                Para12Subheading = _memoryCache.Get<string>("Para12SubheadingField"),
                                Para13Subheading = _memoryCache.Get<string>("Para13SubheadingField"),
                                Para14Subheading = _memoryCache.Get<string>("Para14SubheadingField"),
                                Para15Subheading = _memoryCache.Get<string>("Para15SubheadingField"),
                                Para16Subheading = _memoryCache.Get<string>("Para16SubheadingField"),
                                Para17Subheading = _memoryCache.Get<string>("Para17SubheadingField"),
                                Para18Subheading = _memoryCache.Get<string>("Para18SubheadingField"),
                                Para19Subheading = _memoryCache.Get<string>("Para19SubheadingField"),
                                Para20Subheading = _memoryCache.Get<string>("Para20SubheadingField"),
                                Para21Subheading = _memoryCache.Get<string>("Para21SubheadingField"),
                                Para22Subheading = _memoryCache.Get<string>("Para22SubheadingField"),
                                Para23Subheading = _memoryCache.Get<string>("Para23SubheadingField"),
                                Para24Subheading = _memoryCache.Get<string>("Para24SubheadingField"),
                                Para25Subheading = _memoryCache.Get<string>("Para25SubheadingField"),
                                Para26Subheading = _memoryCache.Get<string>("Para26SubheadingField"),
                                Para27Subheading = _memoryCache.Get<string>("Para27SubheadingField"),
                                Para28Subheading = _memoryCache.Get<string>("Para28SubheadingField"),
                                Para29Subheading = _memoryCache.Get<string>("Para29SubheadingField"),
                                Para30Subheading = _memoryCache.Get<string>("Para30SubheadingField"),
                                Para31Subheading = _memoryCache.Get<string>("Para31SubheadingField"),
                                Para32Subheading = _memoryCache.Get<string>("Para32SubheadingField"),
                                Para33Subheading = _memoryCache.Get<string>("Para33SubheadingField"),
                                Para34Subheading = _memoryCache.Get<string>("Para34SubheadingField"),
                                Para35Subheading = _memoryCache.Get<string>("Para35SubheadingField"),
                                Para36Subheading = _memoryCache.Get<string>("Para36SubheadingField"),
                                Para37Subheading = _memoryCache.Get<string>("Para37SubheadingField"),
                                Para38Subheading = _memoryCache.Get<string>("Para38SubheadingField"),
                                Para39Subheading = _memoryCache.Get<string>("Para39SubheadingField"),
                                Para40Subheading = _memoryCache.Get<string>("Para40SubheadingField"),
                                Para41Subheading = _memoryCache.Get<string>("Para41SubheadingField"),
                                Para42Subheading = _memoryCache.Get<string>("Para42SubheadingField"),
                                Para43Subheading = _memoryCache.Get<string>("Para43SubheadingField"),
                                Para44Subheading = _memoryCache.Get<string>("Para44SubheadingField"),
                                Para45Subheading = _memoryCache.Get<string>("Para45SubheadingField"),
                                Para46Subheading = _memoryCache.Get<string>("Para46SubheadingField"),
                                Para47Subheading = _memoryCache.Get<string>("Para47SubheadingField"),
                                Para48Subheading = _memoryCache.Get<string>("Para48SubheadingField"),
                                Para49Subheading = _memoryCache.Get<string>("Para49SubheadingField"),
                                Para50Subheading = _memoryCache.Get<string>("Para50SubheadingField"),
                                ImageTitleCaption = _memoryCache.Get<string>("ImageTitleCaption"),
                                Image2Caption = _memoryCache.Get<string>("Image2CaptionField"),
                                Image3Caption = _memoryCache.Get<string>("Image3CaptionField"),
                                Image4Caption = _memoryCache.Get<string>("Image4CaptionField"),
                                Image5Caption = _memoryCache.Get<string>("Image5CaptionField"),
                                Image6Caption = _memoryCache.Get<string>("Image6CaptionField"),
                                Image7Caption = _memoryCache.Get<string>("Image7CaptionField"),
                                Image8Caption = _memoryCache.Get<string>("Image8CaptionField"),
                                Image9Caption = _memoryCache.Get<string>("Image9CaptionField"),
                                Image10Caption = _memoryCache.Get<string>("Image10CaptionField"),
                                Image11Caption = _memoryCache.Get<string>("Image11CaptionField"),
                                Image12Caption = _memoryCache.Get<string>("Image12CaptionField"),
                                Image13Caption = _memoryCache.Get<string>("Image13CaptionField"),
                                Image14Caption = _memoryCache.Get<string>("Image14CaptionField"),
                                Image15Caption = _memoryCache.Get<string>("Image15CaptionField"),
                                Image16Caption = _memoryCache.Get<string>("Image16CaptionField"),
                                Image17Caption = _memoryCache.Get<string>("Image17CaptionField"),
                                Image18Caption = _memoryCache.Get<string>("Image18CaptionField"),
                                Image19Caption = _memoryCache.Get<string>("Image19CaptionField"),
                                Image20Caption = _memoryCache.Get<string>("Image20CaptionField"),
                                Image21Caption = _memoryCache.Get<string>("Image21CaptionField"),
                                Image22Caption = _memoryCache.Get<string>("Image22CaptionField"),
                                Image23Caption = _memoryCache.Get<string>("Image23CaptionField"),
                                Image24Caption = _memoryCache.Get<string>("Image24CaptionField"),
                                Image25Caption = _memoryCache.Get<string>("Image25CaptionField"),
                                Image26Caption = _memoryCache.Get<string>("Image26CaptionField"),
                                Image27Caption = _memoryCache.Get<string>("Image27CaptionField"),
                                Image28Caption = _memoryCache.Get<string>("Image28CaptionField"),
                                Image29Caption = _memoryCache.Get<string>("Image29CaptionField"),
                                Image30Caption = _memoryCache.Get<string>("Image30CaptionField"),
                                Image31Caption = _memoryCache.Get<string>("Image31CaptionField"),
                                Image32Caption = _memoryCache.Get<string>("Image32CaptionField"),
                                Image33Caption = _memoryCache.Get<string>("Image33CaptionField"),
                                Image34Caption = _memoryCache.Get<string>("Image34CaptionField"),
                                Image35Caption = _memoryCache.Get<string>("Image35CaptionField"),
                                Image36Caption = _memoryCache.Get<string>("Image36CaptionField"),
                                Image37Caption = _memoryCache.Get<string>("Image37CaptionField"),
                                Image38Caption = _memoryCache.Get<string>("Image38CaptionField"),
                                Image39Caption = _memoryCache.Get<string>("Image39CaptionField"),
                                Image40Caption = _memoryCache.Get<string>("Image40CaptionField"),
                                Image41Caption = _memoryCache.Get<string>("Image41CaptionField"),
                                Image42Caption = _memoryCache.Get<string>("Image42CaptionField"),
                                Image43Caption = _memoryCache.Get<string>("Image43CaptionField"),
                                Image44Caption = _memoryCache.Get<string>("Image44CaptionField"),
                                Image45Caption = _memoryCache.Get<string>("Image45CaptionField"),
                                Image46Caption = _memoryCache.Get<string>("Image46CaptionField"),
                                Image47Caption = _memoryCache.Get<string>("Image47CaptionField"),
                                Image48Caption = _memoryCache.Get<string>("Image48CaptionField"),
                                Image49Caption = _memoryCache.Get<string>("Image49CaptionField"),
                                Image50Caption = _memoryCache.Get<string>("Image50CaptionField"),

                                Image2 = _memoryCache.Get<string>("Image2Url"),
                                Image3 = _memoryCache.Get<string>("Image3Url"),
                                Image4 = _memoryCache.Get<string>("Image4Url"),
                                Image5 = _memoryCache.Get<string>("Image5Url"),
                                Image6 = _memoryCache.Get<string>("Image6Url"),
                                Image7 = _memoryCache.Get<string>("Image7Url"),
                                Image8 = _memoryCache.Get<string>("Image8Url"),
                                Image9 = _memoryCache.Get<string>("Image9Url"),
                                Image10 = _memoryCache.Get<string>("Image10Url"),
                                Image11 = _memoryCache.Get<string>("Image11Url"),
                                Image12 = _memoryCache.Get<string>("Image12Url"),
                                Image13 = _memoryCache.Get<string>("Image13Url"),
                                Image14 = _memoryCache.Get<string>("Image14Url"),
                                Image15 = _memoryCache.Get<string>("Image15Url"),
                                Image16 = _memoryCache.Get<string>("Image16Url"),
                                Image17 = _memoryCache.Get<string>("Image17Url"),
                                Image18 = _memoryCache.Get<string>("Image18Url"),
                                Image19 = _memoryCache.Get<string>("Image19Url"),
                                Image20 = _memoryCache.Get<string>("Image20Url"),
                                Image21 = _memoryCache.Get<string>("Image21Url"),
                                Image22 = _memoryCache.Get<string>("Image22Url"),
                                Image23 = _memoryCache.Get<string>("Image23Url"),
                                Image24 = _memoryCache.Get<string>("Image24Url"),
                                Image25 = _memoryCache.Get<string>("Image25Url"),
                                Image26 = _memoryCache.Get<string>("Image26Url"),
                                Image27 = _memoryCache.Get<string>("Image27Url"),
                                Image28 = _memoryCache.Get<string>("Image28Url"),
                                Image29 = _memoryCache.Get<string>("Image29Url"),
                                Image30 = _memoryCache.Get<string>("Image30Url"),
                                Image31 = _memoryCache.Get<string>("Image31Url"),
                                Image32 = _memoryCache.Get<string>("Image32Url"),
                                Image33 = _memoryCache.Get<string>("Image33Url"),
                                Image34 = _memoryCache.Get<string>("Image34Url"),
                                Image35 = _memoryCache.Get<string>("Image35Url"),
                                Image36 = _memoryCache.Get<string>("Image36Url"),
                                Image37 = _memoryCache.Get<string>("Image37Url"),
                                Image38 = _memoryCache.Get<string>("Image38Url"),
                                Image39 = _memoryCache.Get<string>("Image39Url"),
                                Image40 = _memoryCache.Get<string>("Image40Url"),
                                Image41 = _memoryCache.Get<string>("Image41Url"),
                                Image42 = _memoryCache.Get<string>("Image42Url"),
                                Image43 = _memoryCache.Get<string>("Image43Url"),
                                Image44 = _memoryCache.Get<string>("Image44Url"),
                                Image45 = _memoryCache.Get<string>("Image45Url"),
                                Image46 = _memoryCache.Get<string>("Image46Url"),
                                Image47 = _memoryCache.Get<string>("Image47Url"),
                                Image48 = _memoryCache.Get<string>("Image48Url"),
                                Image49 = _memoryCache.Get<string>("Image49Url"),
                                Image50 = _memoryCache.Get<string>("Image50Url"),
                                Video1 = _memoryCache.Get<string>("Video1Url"),
                                Video2 = _memoryCache.Get<string>("Video2Url"),
                                Video3 = _memoryCache.Get<string>("Video3Url"),
                                Video4 = _memoryCache.Get<string>("Video4Url"),
                                Video5 = _memoryCache.Get<string>("Video5Url"),
                                Video6 = _memoryCache.Get<string>("Video6Url"),
                                Video7 = _memoryCache.Get<string>("Video7Url"),
                                Video8 = _memoryCache.Get<string>("Video8Url"),
                                Video9 = _memoryCache.Get<string>("Video9Url"),
                                Video10 = _memoryCache.Get<string>("Video10Url"),
                                Video11 = _memoryCache.Get<string>("Video11Url"),
                                Video12 = _memoryCache.Get<string>("Video12Url"),
                                Video13 = _memoryCache.Get<string>("Video13Url"),
                                Video14 = _memoryCache.Get<string>("Video14Url"),
                                Video15 = _memoryCache.Get<string>("Video15Url"),
                                Video16 = _memoryCache.Get<string>("Video16Url"),
                                Video17 = _memoryCache.Get<string>("Video17Url"),
                                Video18 = _memoryCache.Get<string>("Video18Url"),
                                Video19 = _memoryCache.Get<string>("Video19Url"),
                                Video20 = _memoryCache.Get<string>("Video20Url"),
                                Video21 = _memoryCache.Get<string>("Video21Url"),
                                Video22 = _memoryCache.Get<string>("Video22Url"),
                                Video23 = _memoryCache.Get<string>("Video23Url"),
                                Video24 = _memoryCache.Get<string>("Video24Url"),
                                Video25 = _memoryCache.Get<string>("Video25Url"),
                                Video26 = _memoryCache.Get<string>("Video26Url"),
                                Video27 = _memoryCache.Get<string>("Video27Url"),
                                Video28 = _memoryCache.Get<string>("Video28Url"),
                                Video29 = _memoryCache.Get<string>("Video29Url"),
                                Video30 = _memoryCache.Get<string>("Video30Url"),
                                Video31 = _memoryCache.Get<string>("Video31Url"),
                                Video32 = _memoryCache.Get<string>("Video32Url"),
                                Video33 = _memoryCache.Get<string>("Video33Url"),
                                Video34 = _memoryCache.Get<string>("Video34Url"),
                                Video35 = _memoryCache.Get<string>("Video35Url"),
                                Video36 = _memoryCache.Get<string>("Video36Url"),
                                Video37 = _memoryCache.Get<string>("Video37Url"),
                                Video38 = _memoryCache.Get<string>("Video38Url"),
                                Video39 = _memoryCache.Get<string>("Video39Url"),
                                Video40 = _memoryCache.Get<string>("Video40Url"),
                                Video41 = _memoryCache.Get<string>("Video41Url"),
                                Video42 = _memoryCache.Get<string>("Video42Url"),
                                Video43 = _memoryCache.Get<string>("Video43Url"),
                                Video44 = _memoryCache.Get<string>("Video44Url"),
                                Video45 = _memoryCache.Get<string>("Video45Url"),
                                Video46 = _memoryCache.Get<string>("Video46Url"),
                                Video47 = _memoryCache.Get<string>("Video47Url"),
                                Video48 = _memoryCache.Get<string>("Video48Url"),
                                Video49 = _memoryCache.Get<string>("Video49Url"),
                                Video50 = _memoryCache.Get<string>("Video50Url"),
                                LikeCount = 0,
                                DislikeCount = 0,
                                SupportCount = 0,
                                QuestionableCount = 0,
                                ShockedCount = 0,
                                Featured = _memoryCache.Get<bool>("featured"),
                                TreePlanted = _memoryCache.Get<bool>("treePurchase"),
                                Context = _context,
                                PostedDateTime = _memoryCache.Get<string>("PostedDateTime"),
                                HomepageShare = "https://twitter.com/intent/tweet?hashtags=gatheringforgood%2Cclimatechange%2Cmakeadifference&original_referer=https%3A%2F%2Fgatheringforgood.com%2F&ref_src=twsrc%5Etfw%7Ctwcamp%5Ebuttonembed%7Ctwterm%5Eshare%7Ctwgr%5E&text=GatheringForGood%20users%20are%20taking%20action%20to%20help%20save%20the%20world!%20Gather%20with%20me%20for%20good%20and%20help%20make%20a%20difference!%20%F0%9F%98%8A&url=https%3A%2F%2Fgatheringforgood.com",
                                GoBack = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceGoBackNameReferenceForPage(),
                                Updates = _locSourceSharedCrossPageNameReferenceLibrary.GetLocSourceUpdatesNameReferenceForPage(),
                                IconTwitter = _SharedCrossPageImageUrlLibrary.GetTwitterIconUrlForPage(),
                                IconLinkedin = _SharedCrossPageImageUrlLibrary.GetLinkedinIconUrlForPage(),
                                IconFacebook = _SharedCrossPageImageUrlLibrary.GetFacebookIconUrlForPage(),
                                FeaturedArticleUrl = _ArticlesPageImageUrls.GetFeaturedNoPaddingArticleImageThumbnailUrlForArticlesPage(),
                                TreePlantedUrl = _TreePurchaseOptionsPartialImageUrls.Get1TreeIconImageThumbnailUrlForAboutPage(),
                                LikeTooltip = _UserArticlePageLocSourceNames.GetLocSourceLikeTooltipNameReferenceForArticlesPage(),
                                DislikeTooltip = _UserArticlePageLocSourceNames.GetLocSourceDislikeTooltipNameReferenceForArticlesPage(),
                                SupportTooltip = _UserArticlePageLocSourceNames.GetLocSourceSupportTooltipNameReferenceForArticlesPage(),
                                QuestionableTooltip = _UserArticlePageLocSourceNames.GetLocSourceQuestionableTooltipNameReferenceForArticlesPage(),
                                ShockedTooltip = _UserArticlePageLocSourceNames.GetLocSourceShockedTooltipNameReferenceForArticlesPage(),
                                GetEarthHandsReducedImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReducedImageUrlForPage(),
                                GetEarthHandsReduced400ImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReduced400ImageUrlForPage(),
                                GetEarthHandsReduced800ImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReduced800ImageUrlForPage(),
                                GetEarthHandsReduced1200ImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReduced1200ImageUrlForPage(),
                                GetEarthHandsReduced1600ImageUrl = _SharedCrossPageImageUrlLibrary.GetEarthHandsReduced1600ImageUrlForPage()
                            };

                        string uploadsFolder = Path.Combine(_env.WebRootPath, "previewimages");

                        DirectoryInfo objDirectoryInfo = new DirectoryInfo(uploadsFolder);
                        foreach (FileInfo File in objDirectoryInfo.GetFiles())
                        {
                            if ((File.LastAccessTime < DateTime.Now.AddMinutes(-2)))
                            {
                                File.Delete();
                            }
                        }

                        return View(viewModel);
                    }
                    catch (Exception e)
                    {
                        Debug.WriteLine(e.GetType().ToString());
                        return LocalRedirect("~/Articles/Articles");
                    }
                } else
                {
                    return LocalRedirect("~/Articles/Articles");
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.GetType().ToString());
                return LocalRedirect("~/Articles/Articles");
            }
        }

        public IActionResult OnGetSetCultureCookie(string cltr, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cltr)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
                );

            return LocalRedirect(returnUrl);
        }

        public async Task<IActionResult> UserReaction(int actionNumber, string path)
        {
            string uniqueRef = path.Substring(path.LastIndexOf("/") + 1);
            await _IncrementUserReaction.incrementReaction(actionNumber, uniqueRef);

            //var formedUrl = "../UserArticle/UserArticle/"

            return Redirect(path);
        }
    }
}