using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LocSourceNameReferenceLibrary
{
    public class CarbonOffsetsPageLocSourceNames
    {
        public string GetLocSourcePageTabTitleNameReferenceForCarbonOffsetsPage()
        {
            string PageTabTitle = "Offset Your Carbon";
            return PageTabTitle;
        }
        public string GetLocSourceTitleNameReferenceForCarbonOffsetsPage()
        {
            string Title = "Offset Your Carbon For A Healthy Planet";
            return Title;
        }
        public string GetLocSourceSubtitleNameReferenceForCarbonOffsetsPage()
        {
            string SubTitle = "Carbon Offsets";
            return SubTitle;
        }
        public string GetLocSourceOffsetMyCarbonNameReferenceForCarbonOffsetsPage()
        {
            string OffsetMyCarbon = "Offset My Carbon";
            return OffsetMyCarbon;
        }
        public string GetLocSourceOffsetAJourneyTitleNameReferenceForCarbonOffsetsPage()
        {
            string Title = "Offset A Journey";
            return Title;
        }
        public string GetLocSourceOffsetByTonneTitleNameReferenceForCarbonOffsetsPage()
        {
            string Title = "Offset By Tonne";
            return Title;
        }
        public string GetLocSourceOffsetMyBusinessCarbonNameReferenceForCarbonOffsetsPage()
        {
            string Title = "Offset Business Carbon";
            return Title;
        }
        public string GetLocSourceTitlePara1NameReferenceForCarbonOffsetsPage()
        {
            string TitlePara1 = "Carbon offsetting with GatheringForGood allows you to invest in carbon negative initiatives worldwide, to help offset the unavoidable carbon emissions created by a persons lifestyle or business. One tonne of carbon dioxide equivalent (CO2e) is approximate equal to the average monthly carbon footprint of someone living in Europe. While carbon offsetting alone is not a solution to the climate crises, the world needs lots of small changes which combined make great changes, and carbon offsetting is widely accepted as a way to be more accountable for your climate impact after having taken steps to reduce your overall carbon footprint.";
            return TitlePara1;
        }
        public string GetLocSourceTitlePara2aNameReferenceForCarbonOffsetsPage()
        {
            string TitlePara2 = "GatheringForGood has partnered with";
            return TitlePara2;
        }

        public string GetLocSourceTitlePara2bNameReferenceForCarbonOffsetsPage()
        {
            string TitlePara2 = ", a leading global climate and sustainability initiative to ensure that your money goes to where it is most effective. Our partnership allows you to plant trees in different locations around the globe which are most meaningful to you, but all of which have a great impact. By offsetting your carbon; the carbon of a friend or family member; your employees carbon; or the carbon generated by your business, you can change your climate impact and influence the front lines of climate change in ways that will have long term benefits for the health of the planet.";
            return TitlePara2;
        }

        public string GetLocSourceOneTreePlantedNameReferenceForCarbonOffsetsPage()
        {
            string TitlePara2 = "OneTreePlanted";
            return TitlePara2;
        }
        public string GetLocSourceOffsetMyCarbonParaNameReferenceForCarbonOffsetsPage()
        {
            string Title = "Offset your carbon, that of your friends and family, or that of your colleagues. Calculate your carbon footprint and choose a location to support a tree planting project which will sequester carbon from the atmosphere. Or just make a one-off contribution to planting, every little helps!";
            return Title;
        }
        public string GetLocSourceOffsetByTonneParaNameReferenceForCarbonOffsetsPage()
        {
            string Title = "Keep it simple! An average European generates 1 tonne of CO2e per month. Offset by the tonne.";
            return Title;
        }
        public string GetLocSourceOffsetAJourneyParaNameReferenceForCarbonOffsetsPage()
        {
            string Title = "Taking a trip? Calculate the carbon impact of your journey, no matter how short or long, and make a difference for the planet by offsetting the carbon your trip generates. Or show that your business pays more than just lip service to sustainability and plant trees against the carbon generated by business trips or your employee commutes.";
            return Title;
        }
        public string GetLocSourceOffsetMyBusinessParaNameReferenceForCarbonOffsetsPage()
        {
            string Title = "Use our comprehensive calculator to establish the unavoidable carbon generated by your business and then help the planet by planting trees to counter-balance what you cant reduce or avoid.";
            return Title;
        }
        public string GetLocSourceOurPartnerTextNameReferenceForCarbonOffsetsPage()
        {
            string Title = "We have partnered with OneTreePlanted to ensure your money has the greatest impact";
            return Title;
        }
        public string GetLocSourceYourMoneyTextNameReferenceForCarbonOffsetsPage()
        {
            string Title = "80% of your money goes to our partners, 20% covers our administration costs";
            return Title;
        }
    }
}
