using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GatheringForGood.Models
{
    public class PrivacyViewModel
    {
        public string PageTabTitle { get; set; }
        public string ButtonText { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string NavBarHome { get; set; }
        public string NavBarNewsfeed { get; set; }
        public string NavBarAbout { get; set; }
        public string NavBarHelpCenter { get; set; }
        public string NavBarRegister { get; set; }
        public string NavBarLogin { get; set; }
        public string NavBarLogout { get; set; }
        public string AboutUs { get; set; }
        public string Articles { get; set; }
        public string CookiesNotice { get; set; }
        public string PrivacyNotice { get; set; }
        public string NameImageThumbnailUrl { get; set; }
        public string YourPrivacyMattersTitle { get; set; }
        public string PrivacyEffectiveDate { get; set; }
        public string PrivacyTableOfContentsTitle { get; set; }
        public string PrivacyIntroductionLink { get; set; }
        public string PrivacyDataWeCollectLink { get; set; }
        public string PrivacyHowWeUseYourDataLink { get; set; }
        public string PrivacyHowWeShareInformationLink { get; set; }
        public string PrivacyChoicesAndObligationsLink { get; set; }
        public string PrivacyOtherInformationLink { get; set; }
        public string YourPrivacyMattersPara1 { get; set; }
        public string YourPrivacyMattersPara2 { get; set; }
        public string IntroductionShortPara { get; set; }
        public string IntroductionPara1 { get; set; }
        public string IntroductionPara2 { get; set; }
        public string IntroductionPara3 { get; set; }
        public string Members { get; set; }
        public string Visitors { get; set; }
        public string ServicesTitle { get; set; }
        public string ServicesShortPara { get; set; }
        public string ServicesPara1 { get; set; }
        public string ServicesPara2 { get; set; }
        public string DataControllersTitle { get; set; }
        public string DataControllersShortPara { get; set; }
        public string DataControllersPara1 { get; set; }
        public string DataControllersPara2 { get; set; }
        public string PolicyChangesTitle { get; set; }
        public string PolicyChangesShortPara { get; set; }
        public string PolicyChangesPara1 { get; set; }
        public string PolicyChangesPara2 { get; set; }
        public string RegistrationTitle { get; set; }
        public string RegistrationShortPara { get; set; }
        public string RegistrationPara1 { get; set; }
        public string ProfileTitle { get; set; }
        public string ProfileShortPara { get; set; }
        public string ProfilePara1 { get; set; }
        public string ProfilePara2 { get; set; }
        public string PostingTitle { get; set; }
        public string PostingShortPara { get; set; }
        public string PostingPara1 { get; set; }
        public string PostingPara2 { get; set; }
        public string PostingPara3 { get; set; }
        public string ContentTitle { get; set; }
        public string ContentShortPara { get; set; }
        public string ContentPara1 { get; set; }
        public string ContactsAndCalendarTitle { get; set; }
        public string ContactsAndCalendarShortPara { get; set; }
        public string ContactsAndCalendarPara1 { get; set; }
        public string CustomersAndPartnersTitle { get; set; }
        public string CustomersAndPartnersShortPara { get; set; }
        public string CustomersAndPartnersPara1 { get; set; }
        public string ServiceUsageTitle { get; set; }
        public string ServiceUsageShortPara { get; set; }
        public string ServiceUsagePara1 { get; set; }
        public string CookiesTitle { get; set; }
        public string CookiesShortPara { get; set; }
        public string CookiesPara1 { get; set; }
        public string CookiesPara2 { get; set; }
        public string CookiesPara3 { get; set; }
        public string CookiePolicy { get; set; }
        public string DevicesAndLocationTitle { get; set; }
        public string DevicesAndLocationShortPara { get; set; }
        public string DevicesAndLocationPara1 { get; set; }
        public string MessagesTitle { get; set; }
        public string MessagesShortPara { get; set; }
        public string MessagesPara1 { get; set; }
        public string MessagesPara2 { get; set; }
        public string MessagesPara3 { get; set; }
        public string TermsConditions { get; set; }
        public string MemberPolicies { get; set; }
        public string SchoolAndOthersInfoTitle { get; set; }
        public string SchoolAndOthersInfoShortPara { get; set; }
        public string SchoolAndOthersInfoPara1 { get; set; }
        public string SchoolAndOthersInfoPara2 { get; set; }
        public string OtherSitesAndServicesTitle { get; set; }
        public string OtherSitesAndServicesShortPara { get; set; }
        public string OtherSitesAndServicesPara1 { get; set; }
        public string OtherDataWeCollectTitle { get; set; }
        public string OtherDataWeCollectShortPara { get; set; }
        public string OtherDataWeCollectPara1 { get; set; }
        public string HowWeUseYourDataShortPara { get; set; }
        public string HowWeUseYourDataPara1 { get; set; }
        public string ConnectAndStayConnectedTitle { get; set; }
        public string ConnectAndStayConnectedShortPara { get; set; }
        public string ConnectAndStayConnectedPara1 { get; set; }
        public string ConnectAndStayConnectedPara2 { get; set; }
        public string ConnectAndStayConnectedPara3 { get; set; }
        public string StayInformedTitle { get; set; }
        public string StayInformedShortPara { get; set; }
        public string StayInformedPara1 { get; set; }
        public string StayInformedPara2 { get; set; }
        public string ProductivityTitle { get; set; }
        public string ProductivityShortPara { get; set; }
        public string ProductivityPara1 { get; set; }
        public string PaidPremiumServicesTitle { get; set; }
        public string PaidPremiumServicesShortPara { get; set; }
        public string PaidPremiumServicesPara1 { get; set; }
        public string PaidPremiumServicesPara2 { get; set; }
        public string CommunicationsTitle { get; set; }
        public string CommunicationsShortPara { get; set; }
        public string CommunicationsPara1 { get; set; }
        public string CommunicationsPara2 { get; set; }
        public string AdvertisingTitle { get; set; }
        public string AdvertisingShortPara { get; set; }
        public string AdvertisingPara1 { get; set; }
        public string AdvertisingPara2 { get; set; }
        public string AdvertisingPara3 { get; set; }
        public string AdvertisingPara4 { get; set; }
        public string AdvertisingPara5 { get; set; }
        public string AdvertisingPara6 { get; set; }
        public string AdvertisingPara7 { get; set; }
        public string AdChoicesTitle { get; set; }
        public string AdChoicesShortPara { get; set; }
        public string AdChoicesPara1 { get; set; }
        public string InfoToAdProvidersTitle { get; set; }
        public string InfoToAdProvidersShortPara { get; set; }
        public string InfoToAdProvidersPara1 { get; set; }
        public string MarketingTitle { get; set; }
        public string MarketingShortPara { get; set; }
        public string MarketingPara1 { get; set; }
        public string ServiceDevelopmentTitle { get; set; }
        public string ServiceDevelopmentShortPara { get; set; }
        public string ServiceDevelopmentPara1 { get; set; }
        public string OtherResearchTitle { get; set; }
        public string OtherResearchShortPara { get; set; }
        public string OtherResearchPara1 { get; set; }
        public string OtherResearchPara2 { get; set; }
        public string PollsAndSurveysTitle { get; set; }
        public string PollsAndSurveysShortPara { get; set; }
        public string PollsAndSurveysPara1 { get; set; }
        public string CustomerSupportTitle { get; set; }
        public string CustomerSupportShortPara { get; set; }
        public string CustomerSupportPara1 { get; set; }
        public string NonIdentifyingInsightsTitle { get; set; }
        public string NonIdentifyingInsightsShortPara { get; set; }
        public string NonIdentifyingInsightsPara1 { get; set; }
        public string SecurityInvestigationsTitle { get; set; }
        public string SecurityInvestigationsShortPara { get; set; }
        public string SecurityInvestigationsPara1 { get; set; }
        public string YourProfileTitle { get; set; }
        public string YourProfileShortPara { get; set; }
        public string YourProfilePara1 { get; set; }
        public string PostsLikesTitle { get; set; }
        public string PostsLikesShortPara { get; set; }
        public string PostsLikesPara1 { get; set; }
        public string PostsLikesPara2 { get; set; }
        public string PostsLikesPara3 { get; set; }
        public string PostsLikesPara4 { get; set; }
        public string PostsLikesPara5 { get; set; }
        public string PostsLikesPara6 { get; set; }
        public string PostsLikesPara7 { get; set; }
        public string EnterpriseAccountsTitle { get; set; }
        public string EnterpriseAccountsShortPara { get; set; }
        public string EnterpriseAccountsPara1 { get; set; }
        public string OthersServicesTitle { get; set; }
        public string OthersServicesShortPara { get; set; }
        public string OthersServicesPara1 { get; set; }
        public string OthersServicesPara2 { get; set; }
        public string RelatedServicesTitle { get; set; }
        public string RelatedServicesShortPara { get; set; }
        public string RelatedServicesPara1 { get; set; }
        public string ServiceProvidersTitle { get; set; }
        public string ServiceProvidersShortPara { get; set; }
        public string ServiceProvidersPara1 { get; set; }
        public string LegalDisclosuresTitle { get; set; }
        public string LegalDisclosuresShortPara { get; set; }
        public string LegalDisclosuresPara1 { get; set; }
        public string LegalDisclosuresPara2 { get; set; }
        public string ChangeInControlTitle { get; set; }
        public string ChangeInControlShortPara { get; set; }
        public string ChangeInControlPara1 { get; set; }
        public string DataRetentionTitle { get; set; }
        public string DataRetentionShortPara { get; set; }
        public string DataRetentionPara1 { get; set; }
        public string DataAccessControlTitle { get; set; }
        public string DataAccessControlShortPara { get; set; }
        public string DataAccessControlPara1 { get; set; }
        public string DataAccessControlPara2 { get; set; }
        public string DataAccessControlPara3 { get; set; }
        public string DataAccessControlPara4 { get; set; }
        public string DeleteData { get; set; }
        public string ChangeData { get; set; }
        public string AccessData { get; set; }
        public string DeleteAccountTitle { get; set; }
        public string DeleteAccountShortPara { get; set; }
        public string DeleteAccountPara1 { get; set; }
        public string DeleteAccountPara2 { get; set; }
        public string DeleteAccountPara3 { get; set; }
        public string SecurityTitle { get; set; }
        public string SecurityShortPara { get; set; }
        public string SecurityPara1 { get; set; }
        public string SecurityPara2 { get; set; }
        public string CrossBorderDataTitle { get; set; }
        public string CrossBorderDataShortPara { get; set; }
        public string CrossBorderDataPara1 { get; set; }
        public string ProcessingLawfulBasisTitle { get; set; }
        public string ProcessingLawfulBasisShortPara { get; set; }
        public string ProcessingLawfulBasisPara1 { get; set; }
        public string ContactUsTitle { get; set; }
        public string ContactUsShortPara { get; set; }
        public string ContactUsPara1 { get; set; }
        public string Submit { get; set; }
        public string ComingSoon { get; set; }
        public string LikeToSee { get; set; }
        public string Updates { get; set; }
        public string HomepageShare { get; set; }
        public string IconTwitter { get; set; }
        public string IconLinkedin { get; set; }
        public string IconFacebook { get; set; }
        public string GetEarthHandsReducedImageUrl { get; set; }
        public string GetEarthHandsReduced400ImageUrl { get; set; }
        public string GetEarthHandsReduced800ImageUrl { get; set; }
        public string GetEarthHandsReduced1200ImageUrl { get; set; }
        public string GetEarthHandsReduced1600ImageUrl { get; set; }
    }
}
