using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GatheringForGood.Models
{
    public class ReduceGlobalWarmingViewModel
    {
        public string PageTabTitle { get; set; }
        public string ButtonText { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string DoSomethingTodayTitle { get; set; }
        public string DoSomethingTodayPara { get; set; }
        public string DoSomethingTodayPara2 { get; set; }
        public string AllUserActionsIcon { get; set; }
        public string AllUserRGWActionsIcon { get; set; }
        public string MyTotalActionsIcon { get; set; }
        public string MyCO2ImpactIcon { get; set; }
        public string RGWMyCO2ImpactTitle { get; set; }
        public string RGWMyCO2ImpactTotal { get; set; }
        public string AllUsersCO2ImpactTitle { get; set; }
        public string AllUsersCO2ImpactTotal { get; set; }
        public string AllUsersCO2ImpactIcon { get; set; }
        public string AllUsersCO2MyShare { get; set; }
        public string WhatCanIDo { get; set; }
        public string Information { get; set; }
        public string Impact { get; set; }
        public string IDidThisToday { get; set; }
        public string MyImpact { get; set; }
        public string ReduceMeatIntakeTitle { get; set; }
        public string ReduceMeatIntakePara2 { get; set; }
        public string SixtyPercent { get; set; }
        public string PlantSomeTreesTitle { get; set; }
        public string PlantSomeTreesPara2 { get; set; }
        public string PlantSomeTreesPara3 { get; set; }
        public string EatOrganicTitle { get; set; }
        public string EatOrganicPara1 { get; set; }
        public string GoVegetarianTitle { get; set; }
        public string GoVegetarianPara1 { get; set; }
        public string GoVeganTitle { get; set; }
        public string GoVeganPara1 { get; set; }
        public string LiveCarFreeTitle { get; set; }
        public string LiveCarFree { get; set; }
        public string GreenRecoveryTitle { get; set; }
        public string GreenRecoveryPara1 { get; set; }
        public string MinimisePlasticTitle { get; set; }
        public string MinimisePlasticPara1 { get; set; }
        public string BuyLocalTitle { get; set; }
        public string BuyLocal { get; set; }
        public string CycleTitle { get; set; }
        public string IncreaseCycling { get; set; }
        public string DriveElectricTitle { get; set; }
        public string DriveElectricPara1 { get; set; }
        public string PlantYourOwnVegTitle { get; set; }
        public string PlantYourOwnVegPara1 { get; set; }
        public string SwitchToRenewableTitle { get; set; }
        public string SwitchToRenewablePara1 { get; set; }
        public string UsePublicTransportTitle { get; set; }
        public string IncreasePublicTransport1 { get; set; }
        public string IncreasePublicTransport2 { get; set; }
        public string CarPoolTitle { get; set; }
        public string IncreaseCarpooling { get; set; }
        public string FlyLessOftenTitle { get; set; }
        public string FlyLessOftenPara1 { get; set; }
        public string StandUp { get; set; }
        public string StandUpPara1 { get; set; }
        public string UseABlueRecyclingBinTitle { get; set; }
        public string UseABlueRecyclingBinPara1 { get; set; }
        public string UseABrownCompostBinTitle { get; set; }
        public string UseABrownCompostBinPara1 { get; set; }
        public string InsulateYourHouseTitle { get; set; }
        public string InsulateYourHousePara1 { get; set; }
        public string ShorterShowers { get; set; }
        public string ShorterShowersPara1 { get; set; }
        public string FluorescentLightbulbs { get; set; }
        public string FluorescentLightbulbsPara1 { get; set; }
        public string TurnOffLights { get; set; }
        public string TurnOffLightsPara1 { get; set; }
        public string SignAPetitionTitle { get; set; }
        public string SignAPetitionPara1 { get; set; }
        public string ComingSoon { get; set; }
        public string WhatDidYouExpectPara { get; set; }
        public string LearnMore { get; set; }
        public string NavBarHome { get; set; }
        public string NavBarNewsfeed { get; set; }
        public string NavBarAbout { get; set; }
        public string NavBarHelpCenter { get; set; }
        public string NavBarRegister { get; set; }
        public string NavBarLogin { get; set; }
        public string NavBarLogout { get; set; }
        public string AboutUs { get; set; }
        public string Articles { get; set; }
        public string CookiesNotice { get; set; }
        public string PrivacyNotice { get; set; }
        public string CanopyProjectUrl { get; set; }
        public string Co2icon1 { get; set; }
        public string Co2icon2 { get; set; }
        public string Co2icon3 { get; set; }
        public string Co2icon4 { get; set; }
        public string Co2icon5 { get; set; }
        public string MouseClickIconThumbnailUrl { get; set; }
        public string HandTapIconThumbnailUrl { get; set; }
        public string Close { get; set; }
        public string MyImpactReduceMeat { get; set; }
        public string MyImpactPlantTrees { get; set; }
        public string MyImpactEatOrganic { get; set; }
        public string MyImpactGoVegetarian { get; set; }
        public string MyImpactGoVegan { get; set; }
        public string MyImpactLiveCarFree { get; set; }
        public string MyImpactGreenRecovery { get; set; }
        public string MyImpactMinimisePlastic { get; set; }
        public string MyImpactBuyLocal { get; set; }
        public string MyImpactCycle { get; set; }
        public string MyImpactDriveElectric { get; set; }
        public string MyImpactPlantOwnVeg { get; set; }
        public string MyImpactSwitchRenewable { get; set; }
        public string MyImpactPublicTransport { get; set; }
        public string MyImpactCarPool { get; set; }
        public string MyImpactFlyLess { get; set; }
        public string MyImpactStandUp { get; set; }
        public string MyImpactRecyclingBin { get; set; }
        public string MyImpactCompostBin { get; set; }
        public string MyImpactInsulateHouse { get; set; }
        public string MyImpactShorterShowers { get; set; }
        public string MyImpactFluorescent { get; set; }
        public string MyImpactTurnOffLights { get; set; }
        public string MyImpactSignPetition { get; set; }
        public string SiteImpactTotal { get; set; }
        public string RGWImpactTotal { get; set; }
        public string UserImpactTotal { get; set; }
        public string SiteImpactTitle { get; set; }
        public string RGWImpactTitle { get; set; }
        public string UserImpactTitle { get; set; }
        public string Submit { get; set; }
        public string LikeToSee { get; set; }
        public string ReduceGlobalWarmingButton { get; set; }
        public string ReduceExtinctionButton { get; set; }
        public string ReduceDeforestationButton { get; set; }
        public string EnableSharing { get; set; }
        public bool EnableSharingCheckbox { get; set; }
        public string TotalActionsAllUsersShare { get; set; }
        public string GlobalWarmingAllUsersShare { get; set; }
        public string TotalActionsMyShare { get; set; }
        public string CO2ReductionMyShare { get; set; }
        public string IconTwitter { get; set; }
        public string IconLinkedin { get; set; }
        public string IconFacebook { get; set; }
        public string IconReddit { get; set; }
        public string ClickDetails { get; set; }
        public string ReduceMeatClickDetails { get; set; }
        public string MinimisePlasticClickDetails { get; set; }
        public string GoVegetarianClickDetails { get; set; }
        public string GoVeganClickDetails { get; set; }
        public string NotQuantifiableClickDetails { get; set; }
        public string RecyclingBinClickDetails { get; set; }
        public string PlantSomeTreesClickDetails { get; set; }
        public string EatOrganicClickDetails { get; set; }
        public string LiveCarFreeClickDetails { get; set; }
        public string BuyLocalClickDetails { get; set; }
        public string CycleClickDetails { get; set; }
        public string DriveElectricClickDetails { get; set; }
        public string PlantYourOwnVegClickDetails { get; set; }
        public string UsePublicTransportClickDetails { get; set; }
        public string CarpoolClickDetails { get; set; }
        public string InsulateYourHouseClickDetails { get; set; }
        public string ShorterShowersClickDetails { get; set; }
        public string FluorescentLightbulbsClickDetails { get; set; }
        public string TurnOffLightsClickDetails { get; set; }
        public string RDFIconImage { get; set; }
        public string RDFIconText { get; set; }
        public string RAEIconImage { get; set; }
        public string RAEIconText { get; set; }
        public string RGWIconImage { get; set; }
        public string RGWIconText { get; set; }
        public string Updates { get; set; }
        public string HomepageShare { get; set; }
        public string RGWpageShare { get; set; }
        public string GetEarthHandsReducedImageUrl { get; set; }
        public string GetEarthHandsReduced400ImageUrl { get; set; }
        public string GetEarthHandsReduced800ImageUrl { get; set; }
        public string GetEarthHandsReduced1200ImageUrl { get; set; }
        public string GetEarthHandsReduced1600ImageUrl { get; set; }
    }
}
