using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GatheringForGood.Models
{
    public class ReduceDeforestationViewModel
    {
        public string PageTabTitle { get; set; }
        public string ButtonText { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string DoSomethingTodayTitle { get; set; }
        public string DoSomethingTodayPara { get; set; }
        public string DoSomethingTodayPara2 { get; set; }
        public string AllUserActionsIcon { get; set; }
        public string AllUserRDFActionsIcon { get; set; }
        public string AllUsersCO2ImpactTitle { get; set; }
        public string AllUsersCO2ImpactTotal { get; set; }
        public string AllUsersCO2ImpactIcon { get; set; }
        public string AllUsersCO2MyShare { get; set; }
        public string MyTotalActionsIcon { get; set; }
        public string MyCO2ImpactIcon { get; set; }
        public string RDFMyCO2ImpactTitle { get; set; }
        public string RDFMyCO2ImpactTotal { get; set; }
        public string WhatCanIDo { get; set; }
        public string Information { get; set; }
        public string Impact { get; set; }
        public string IDidThisToday { get; set; }
        public string ReduceMeatIntakeTitle { get; set; }
        public string ReduceMeatIntakePara1 { get; set; }
        public string ReduceMeatIntakePara2 { get; set; }
        public string DonateTitle { get; set; }
        public string DonatePara1 { get; set; }
        public string SocialMediaTitle { get; set; }
        public string SocialMediaPara1 { get; set; }
        public string SupportHabitatRestorationTitle { get; set; }
        public string SupportHabitatRestorationPara1 { get; set; }
        public string SupportHabitatRestorationPara2 { get; set; }
        public string PlantSomeTreesTitle { get; set; }
        public string PlantSomeTreesPara1 { get; set; }
        public string PlantSomeTreesPara2 { get; set; }
        public string GoPaperlessTitle { get; set; }
        public string GoPaperlessPara1 { get; set; }
        public string EatOrganicTitle { get; set; }
        public string EatOrganicPara1 { get; set; }
        public string ZeroDeforestationTitle { get; set; }
        public string ZeroDeforestationPara1 { get; set; }
        public string BuyRecycledTitle { get; set; }
        public string BuyRecycledPara1 { get; set; }
        public string StandUpTitle { get; set; }
        public string StandUpPara1 { get; set; }
        public string GoVegetarianTitle { get; set; }
        public string GoVegetarianPara1 { get; set; }
        public string GoVeganTitle { get; set; }
        public string GoVeganPara1 { get; set; }
        public string SignAPetitionTitle { get; set; }
        public string SignAPetitionPara1 { get; set; }
        public string ComingSoon { get; set; }
        public string WhatDidYouExpectPara { get; set; }
        public string LearnMore { get; set; }
        public string NavBarHome { get; set; }
        public string NavBarNewsfeed { get; set; }
        public string NavBarAbout { get; set; }
        public string NavBarHelpCenter { get; set; }
        public string NavBarRegister { get; set; }
        public string NavBarLogin { get; set; }
        public string NavBarLogout { get; set; }
        public string AboutUs { get; set; }
        public string Articles { get; set; }
        public string CookiesNotice { get; set; }
        public string PrivacyNotice { get; set; }
        public string CanopyProjectUrl { get; set; }
        public string Treeicon1 { get; set; }
        public string Treeicon2 { get; set; }
        public string Treeicon3 { get; set; }
        public string Treeicon4 { get; set; }
        public string Treeicon5 { get; set; }
        public string MouseClickIconThumbnailUrl { get; set; }
        public string HandTapIconThumbnailUrl { get; set; }
        public string Close { get; set; }
        public string MyImpact { get; set; }
        public string MyImpactReduceMeat { get; set; }
        public string MyImpactGoVegetarian { get; set; }
        public string MyImpactGoVegan { get; set; }
        public string MyImpactEatOrganic { get; set; }
        public string MyImpactHabitatRestoration { get; set; }
        public string MyImpactZeroDeforestation { get; set; }
        public string MyImpactGoPaperless { get; set; }
        public string MyImpactDonate { get; set; }
        public string MyImpactPlantTrees { get; set; }
        public string MyImpactBuyRecycled { get; set; }
        public string MyImpactStandUp { get; set; }
        public string MyImpactSignAPetition { get; set; }
        public string MyImpactSocialMedia { get; set; }
        public string SiteImpactTotal { get; set; }
        public string RDFImpactTotal { get; set; }
        public string UserImpactTotal { get; set; }
        public string SiteImpactTitle { get; set; }
        public string RDFImpactTitle { get; set; }
        public string UserImpactTitle { get; set; }
        public string Submit { get; set; }
        public string LikeToSee { get; set; }
        public string ReduceGlobalWarmingButton { get; set; }
        public string ReduceExtinctionButton { get; set; }
        public string ReduceDeforestationButton { get; set; }
        public string EnableSharing { get; set; }
        public bool EnableSharingCheckbox { get; set; }
        public string TotalActionsAllUsersShare { get; set; }
        public string GlobalWarmingAllUsersShare { get; set; }
        public string TotalActionsMyShare { get; set; }
        public string CO2ReductionMyShare { get; set; }
        public string IconTwitter { get; set; }
        public string IconLinkedin { get; set; }
        public string IconFacebook { get; set; }
        public string IconReddit { get; set; }
        public string ClickDetails { get; set; }
        public string ReduceMeatClickDetails { get; set; }
        public string GoVegetarianClickDetails { get; set; }
        public string GoVeganClickDetails { get; set; }
        public string NotQuantifiableClickDetails { get; set; }
        public string EatOrganicClickDetails { get; set; }
        public string HabitatRestorationClickDetails { get; set; }
        public string ZeroDeforestationClickDetails { get; set; }
        public string GoPaperlessClickDetails { get; set; }
        public string DonateClickDetails { get; set; }
        public string PlantSomeTreesClickDetails { get; set; }
        public string BuyRecycledClickDetails { get; set; }
        public string StandUpClickDetails { get; set; }
        public string SignPetitionDetails { get; set; }
        public string SocialMediaClickDetails { get; set; }
        public string RDFIconImage { get; set; }
        public string RDFIconText { get; set; }
        public string RAEIconImage { get; set; }
        public string RAEIconText { get; set; }
        public string RGWIconImage { get; set; }
        public string RGWIconText { get; set; }
        public string Updates { get; set; }
        public string HomepageShare { get; set; }
        public string RDFpageShare { get; set; }
        public string GetEarthHandsReducedImageUrl { get; set; }
        public string GetEarthHandsReduced400ImageUrl { get; set; }
        public string GetEarthHandsReduced800ImageUrl { get; set; }
        public string GetEarthHandsReduced1200ImageUrl { get; set; }
        public string GetEarthHandsReduced1600ImageUrl { get; set; }
    }
}