using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GatheringForGood.Models
{
    public class UpdatesViewModel
    {
        public string PageTabTitle { get; set; }
        public string ButtonText { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string NavBarHome { get; set; }
        public string NavBarNewsfeed { get; set; }
        public string NavBarAbout { get; set; }
        public string NavBarHelpCenter { get; set; }
        public string NavBarRegister { get; set; }
        public string NavBarLogin { get; set; }
        public string NavBarLogout { get; set; }
        public string AboutUs { get; set; }
        public string UpdatesHeading { get; set; }
        public string UpdatesHeadingPara { get; set; }
        public string Articles { get; set; }
        public string CookiesNotice { get; set; }
        public string PrivacyNotice { get; set; }
        public string Submit { get; set; }
        public string ComingSoon { get; set; }
        public string LikeToSee { get; set; }
        public string Updates { get; set; }
        public string Date { get; set; }
        public string Details { get; set; }
        public string UserFeedback { get; set; }
        public string Yes { get; set; }
        public string No { get; set; }
        public string CheckGreen { get; set; }
        public string Row1 { get; set; }
        public string Row2 { get; set; }
        public string Row3 { get; set; }
        public string Row4 { get; set; }
        public string Row5 { get; set; }
        public string Row6 { get; set; }
        public string Row7 { get; set; }
        public string Row8 { get; set; }
        public string Row9 { get; set; }
        public string Row10 { get; set; }
        public string Row11 { get; set; }
        public string Row12 { get; set; }
        public string Row13 { get; set; }
        public string Row14 { get; set; }
        public string Row15 { get; set; }
        public string Row16 { get; set; }
        public string Row17 { get; set; }
        public string Row18 { get; set; }
        public string Row19 { get; set; }
        public string Row20 { get; set; }
        public string Row21 { get; set; }
        public string Row22 { get; set; }
        public string Row23 { get; set; }
        public string Row24 { get; set; }
        public string Row25 { get; set; }
        public string Row26 { get; set; }
        public string Row27 { get; set; }
        public string Row28 { get; set; }
        public string Row29 { get; set; }
        public string Row30 { get; set; }
        public string Row31 { get; set; }
        public string Row32 { get; set; }
        public string Row33 { get; set; }
        public string Row34 { get; set; }
        public string Row35 { get; set; }
        public string Row36 { get; set; }
        public string Row37 { get; set; }
        public string Row38 { get; set; }
        public string Row39 { get; set; }
        public string Row40 { get; set; }
        public string Row41 { get; set; }
        public string Row42 { get; set; }
        public string Row43 { get; set; }
        public string Row44 { get; set; }
        public string Row45 { get; set; }
        public string Row46 { get; set; }
        public string Row47 { get; set; }
        public string Row48 { get; set; }
        public string Row49 { get; set; }
        public string Row50 { get; set; }
        public string Row51 { get; set; }
        public string Row52 { get; set; }
        public string Row53 { get; set; }
        public string Row54 { get; set; }
        public string Row55 { get; set; }
        public string Row56 { get; set; }
        public string Row57 { get; set; }
        public string Row58 { get; set; }
        public string Row59 { get; set; }
        public string Row60 { get; set; }
        public string Row61 { get; set; }
        public string Row62 { get; set; }
        public string Row63 { get; set; }
        public string Row64 { get; set; }
        public string Row65 { get; set; }
        public string Row66 { get; set; }
        public string Row67 { get; set; }
        public string Row68 { get; set; }
        public string Row69 { get; set; }
        public string Row70 { get; set; }
        public string Row71 { get; set; }
        public string Row72 { get; set; }
        public string Row73 { get; set; }
        public string Row74 { get; set; }
        public string Row75 { get; set; }
        public string Row76 { get; set; }
        public string Row77 { get; set; }
        public string Row78 { get; set; }
        public string Row79 { get; set; }
        public string Row80 { get; set; }
        public string Row81 { get; set; }
        public string Row82 { get; set; }
        public string Row83 { get; set; }
        public string Row84 { get; set; }
        public string Row85 { get; set; }
        public string Row86 { get; set; }
        public string Row87 { get; set; }
        public string Row88 { get; set; }
        public string Row89 { get; set; }
        public string Row90 { get; set; }
        public string Row91 { get; set; }
        public string Row94 { get; set; }
        public string HomepageShare { get; set; }
        public string IconTwitter { get; set; }
        public string IconLinkedin { get; set; }
        public string IconFacebook { get; set; }
        public string GetEarthHandsReducedImageUrl { get; set; }
        public string GetEarthHandsReduced400ImageUrl { get; set; }
        public string GetEarthHandsReduced800ImageUrl { get; set; }
        public string GetEarthHandsReduced1200ImageUrl { get; set; }
        public string GetEarthHandsReduced1600ImageUrl { get; set; }
    }
}
